### update an existing patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name" : "john t1",
  "email" : "test5@example.com",
  "address" : "123 donnowhere street",
  "dateOfBirth" : "1998-12-03"
}

###